-- First, remove the table if it exists
drop table if exists bookmarks;

-- Create the table anew
create table bookmarks (
  id INTEGER primary key generated by default as identity,
  title text NOT NULL,
  url text NOT NULL,
  rating INTEGER
);

-- insert some test data
-- Using a multi-row insert statement here
insert into bookmarks (title, url, rating)
values
  ('Facebook', 'https://www.facebook.com/', 1),
  ('Google', 'https://www.google.com/', 3),
  ('Instagram', 'https://www.instagram.com/', 2),
  ('CNN', 'https://www.cnn.com/', 2),
  ('NBA', 'https://www.nba.com/', 5),
  ('Pitchfork', 'https://pitchfork.com/', 4),
  ('Amazon', 'https://www.amazon.com/', 2),
  ('Gmail', 'https://www.gmail.com/', 3),
  ('GitHub', 'https://github.com/', 4);